eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/

server:
  port: 6001

feign:
#  httpclient:
#    enabled: true
  hystrix:
    enabled: true

spring:
    application:
        name: pay-web
    datasource:
        name: test
        url: jdbc:mysql://192.168.78.128:3306/mytest?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    aop:
      auto: true
      proxy-target-class: true
    redis:
        database: 0
        host: 192.168.78.128
        password:
        pool:
            max-active: 200
            max-idle: 10
            max-wait: 1
            min-idle: 0
        port: 6379
        timeout: 1000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.work.generaldb.model
  #mybatis打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


