eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/

spring:
  application:
    name: service-zuul

server:
  port: 9999

zuul:
  routes:
    feign:
      path: /pay-web/**
      serviceId: pay-web

#路由超时，即socket超时设置
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1
#hystrix超时
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 90000