eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/

spring:
  application:
    name: service-zuul

server:
  port: 9999

zuul:
  routes:
    feign:
      path: /pay-web/**
      serviceId: pay-web

ribbon:
  ReadTimeout: 10000
  SocketTimeOut: 10000