eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1001/eureka/

spring:
  application:
    name: service-kafka
  aop:
    auto: true
    proxy-target-class: true

server:
  port: 7002

